### ISSUE TITLE
Output getting truncated

### ISSUE THREAD

**Issue by ssfrr** [willwhitney/hydrogen#89]
![image](https://cloud.githubusercontent.com/assets/734386/8839457/817fd69a-30a3-11e5-8ad0-f28a7f7e13ea.png)

This is particularly an issue when there are helpful line numbers in the info.

Here's what I added to my style.css:

```less
.hydrogen.output-bubble .bubble-output-container {
  display: inline-block;
  max-width: 700px; // make the output a little wider
  max-height: 500px;
  overflow: auto; // shows scrollbars if content is still too big
}

.hydrogen.output-bubble.multiline:not(.rich) .bubble-output-container {
  padding: 3px;
  padding-right: 15px; // make room for possible scroll bar
}
```
